### ISSUE TITLE
Command line wrapper problem when launching mutattion tests

### ISSUE THREAD

**Issue by Aleridia** [valantic/mutation-tester#11]
Hello,

Firstly thank you for this nice plugins.

I installed the last version of it in the IntelliJ 2022.2 Community Edition.

When launching mutation tests, I got this error : 

```
`CommandLineWrapper` is ill-suited for launching apps on Java 9+.
If the run configuration uses "classpath file", please change it to "@argfile".
Otherwise, please contact support.
```

Here is the command launched before the error by the plugin : 
```
xx/tools/jdk-11.0.2/bin/java -Dvisualvm.id=8229697675761917 -javaagent:/usr/local/lib/idea/lib/idea_rt.jar=35859:/usr/local/lib/idea/bin -Dfile.encoding=UTF-8 -classpath /usr/local/lib/idea/lib/idea_rt.jar com.intellij.rt.execution.CommandLineWrapper /tmp/idea_classpath606302401 org.pitest.mutationtest.commandline.MutationCoverageReport --targetClasses fr.targetclass.* --targetTests fr.targetclass.* --reportDir xx/result/2023-02-10-16-35-48 --mutators DEFAULTS --timeoutConst 4000 --outputFormats HTML --excludedClasses *Test* --timeoutFactor 1.25 --maxMutationsPerClass 0 --testPlugin junit --timestampedReports=false --includeLaunchClasspath=true --verbose=false --failWhenNoMutations=true
```

And here are the pom elements : 
```
<dependency>
    <groupId>org.pitest</groupId>
    <artifactId>pitest-junit5-plugin</artifactId>
    <version>1.1.2</version>
</dependency>
```
```
  <plugin>
      <groupId>org.pitest</groupId>
      <artifactId>pitest-maven</artifactId>
      <version>1.11.0</version>
      <dependencies>
          <dependency>
              <groupId>org.pitest</groupId>
              <artifactId>pitest-junit5-plugin</artifactId>
              <version>1.1.2</version>
          </dependency>
      </dependencies>
  </plugin>
``` 
Thank you in advance for you help :)

**Comment by fhuesig** [comment]
Hi there,
I am aware of the error, thank you for the issue. I know the reason for it was a fix i tried to create for the windows users. As a temporary fix i recommend use an older version from the release section in this github repo. A Fix will be comming at the end of the month.

**Comment by Aleridia** [comment]
Thanks for the workaroud !

**Comment by caay2000** [comment]
I'm still having the same problem with version 1.2 from December, so I understand the new version didn't see the light

**Comment by fhuesig** [comment]
Hi all,
so i created a fix for that now. I had replies from windows and unix users and everytime i tried to fix something it had negative effects for the other. So for now the plugin creates a classpathfile which will be used for the command line tool. This way it works for all OS and has no limit on the length of the classpath string. The updated version of the plugin will be in the intellij store in a few hours (up to 24hours)
