### ISSUE TITLE
Request: support for JUnit5

### ISSUE THREAD

**Issue by Danman85** [valantic/mutation-tester#12]
Hello,

I installed the plugin recently and enjoying it, except for the fact that JUnit5 is not supported:

```
8:36:55 AM PIT >> INFO : Verbose logging is disabled. If you encounter a problem, please enable it before reporting an issue.
8:36:56 AM PIT >> WARNING : JUnit 5 is on the classpath but the pitest junit 5 plugin is not installed (https://github.com/pitest/pitest-junit5-plugin)
8:36:57 AM PIT >> INFO : Incremental analysis reduced number of mutations by 0
8:36:57 AM PIT >> INFO : Created 1 mutation test units in pre scan
8:36:58 AM PIT >> INFO : Sending 1 test classes to minion
8:36:58 AM PIT >> INFO : Sent tests to minion
8:36:58 AM PIT >> INFO : Calculated coverage in 1 seconds.
8:36:59 AM PIT >> INFO : Incremental analysis reduced number of mutations by 0
8:36:59 AM PIT >> INFO : Created 1 mutation test units
/================================================================================
8:36:59 AM PIT >> INFO : Completed in 3 seconds
```

Could you add support for that?

Thanks in advance.

**Comment by fhuesig** [comment]
Hello,
so i took a look at it and tried to integrate it into the project. I added the pitest-junit5-plugin and the jupiter and vintage engine. But the tests dont have any line coverage in the reports anymore. I tried to update the option --testPlugin to junit5 like in the gradle/maven version explained, but that didnt do the trick. I doublechecked and the option --testPlugin is not changeable in the command line so it always defaults to junit. So at this point i can not integrate junit5. I will contact Henry from pitest and maybe he got a solution. So i might get back to you in a few days

**Comment by fhuesig** [comment]
i opened a new issue here until then we have to wait:

https://github.com/pitest/pitest-junit5-plugin/issues/80

**Comment by fhuesig** [comment]
maybe its just command line related so i opened here an issue as well https://github.com/hcoles/pitest/issues/1196

**Comment by fhuesig** [comment]
I got some feedback on the ticket but it seems it still doesnt work correctly. I am still on it and will let you know as soon as i got some news.

**Comment by fhuesig** [comment]
Hi,
so i got a response on the pitest ticket from Henry. It was not quite the solution i was looking for but it was a big helpful step. So i figured out the solution and could successfully integrate junit5 into the plugin. In Intellij it will be available in the next 24hours. Otherwise its also in this github as release 1.4.0

**Comment by Danman85** [comment]
@fhuesig thanks!
