### ISSUE TITLE
Configuration template does not apply to tests

### ISSUE THREAD

**Issue by DTselikis** [valantic/mutation-tester#13]
When creating a new test using the "mutation tests" option from context menu, either from inside a test class or from project panel, the advanced parameters that have been set to the "Mutation Testing" configuration template do not apply and you have to set them by hand each time. The only case that the template's configurations **do** apply is when creating a new "Mutation Testing" configuration manually, from "Run/Debug Configurations".
I suppose this is not the intented behavior.

Plugin version:
1.2.0

IntelliJ version:
IntelliJ IDEA 2022.3.3 (Ultimate Edition) Build IU-223.8836.41

**Comment by fhuesig** [comment]
thank you for reporting the issue. i updated it and now the values are correctly applied from the template. The Plugin will be available in the updated version in a few hours (up to 24 hours).
