### ISSUE TITLE
Mutate test with kotlin/Junit5

### ISSUE THREAD

**Issue by tvalli4sh** [valantic/mutation-tester#9]
Hello,

Thanks for your plugin. It's exactly what i've been looking for.

I'm also working on backend projects with kotlin / junit5 and it doesn't seem to work in this setup.

When i try to execute "mutate test" from a test i've got the following error :
![image](https://user-images.githubusercontent.com/90613227/190682738-c75e4001-bbcc-4634-99d0-30f2e3ce6b5d.png)

It doesn't seem to find the class file and the package.

If i set the package manually, it runs but without executing the tests.

I tried to add "verbose" in the configuration and it printed (among others things) :
18:05:54 PIT >> INFO : -kotlin         Support for mutating kotlin bytecode

So is there a way to make your plugin work with kotlin ?

Regards

**Comment by fhuesig** [comment]
Hello there,
thanks for your Feedback. I am not so familiar with kotlin (just basics) but i think i can find a solution for your Problem. I will reproduce it. I am gonna check it out the next days and come back with some feedback. I had an similar issue earlier.

**Comment by fhuesig** [comment]
I identified the problem already. But to make sure can you send a screenshot of your mutation configuration (In your Run/Debug Configuration) to verify

**Comment by fhuesig** [comment]
Otherwise i created a branch for your fix. Would be awesome if you tried out the plugin. It is a pre-release and not jet in the IntelliJ Marketplace. You can download it here -> https://github.com/valantic/mutation-tester/releases/tag/v1.1.2 and install it in IntelliJ locally.

Feedback would be awesome. ty!

**Comment by tvalli4sh** [comment]
I tried to install manually the v1.1.2 but it's the same result.

It doesn't seem to find the tests which are in src/test/kotlin/*package*...

Here is the run configuration that i manually created :
<img width="817" alt="image" src="https://user-images.githubusercontent.com/90613227/194593747-db6af85b-bc84-44ef-a533-c769b48f5ab4.png">

**Comment by fhuesig** [comment]
okay i am back on it

**Comment by fhuesig** [comment]
i have to close this issue. This plugin will preimary target java projects. You can create a fork of this project with the kotlin-pitest plugin from https://github.com/pitest/pitest-kotlin. That plugin is not maintained so we will not create an additional plugin based on that.
